name: action_ref example
description: action_ref example
runs:
  using: composite
  steps:
    - env:
        action_ref: ${{ github.action_ref }}
      run: |
        echo "action_ref=${{ env.action_ref }}"
      shell: bash
