name: test composite action with github.action_ref and github.action_repository
description: test composite action with github.action_ref and github.action_repository
outputs:
  foo:
    description: This action's foo
    value: ${{ steps.extract-action-info.outputs.foo }}
  action_ref:
    description: This action's ref
    value: ${{ steps.extract-action-info.outputs.action_ref }}
  action_repository:
    description: This action's repository
    value: ${{ steps.extract-action-info.outputs.action_repository }}
runs:
  using: composite
  steps:
    - id: extract-action-info
      env:
        my_foo: FOO
        my_action_ref: ${{ github.action_ref }}
        my_action_repository: ${{ github.action_repository }}
      run: |
        env|grep GITHUB
        echo "action_ref1=${{ env.my_action_ref }}"
        echo "action_ref2=$GITHUB_ACTION_REF"
        echo "foo=$my_foo" >> $GITHUB_OUTPUT
        echo "action_ref=$my_action_ref" >> $GITHUB_OUTPUT
        echo "action_repository=$my_action_repository" >> $GITHUB_OUTPUT
      shell: bash
